version: "3.5"
services:
  # Orion is the context broker
  orion:
    image: fiware/orion-ld
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    expose:
      - "1026"
    ports:
      - "80:1026" 
    command: -dbhost mongo-db -logLevel DEBUG
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1

  # Databases
  mongo-db:
    image: mongo:3.6
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017" 
    command: --nojournal
    volumes:
      - mongo-db:/data
  
  # orion-backend:
  #   build:
  #     context: ../
  #     dockerfile: dockerfiles/Dockerfile.backend
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ../backend:/app  # Hot reload: map local 'backend' directory to '/app' in the container
  #   environment:
  #     - NODE_ENV=development
  #   command: npm run dev 

volumes:
  mongo-db: ~
