version: "3.5"

volumes:
    mongodb: ~

services:
  ################
  # Applications #
  ################

  # Context Broker
  scorpio:
    image: scorpiobroker/all-in-one-runner:java-latest
    ports:
      - "1026:9090"
    environment:
      DBHOST: postgres
    depends_on:
      - postgres

  # MQTT Broker for IOT Agent
  mosquitto:
      image: eclipse-mosquitto:latest
      container_name: mosquitto
      ports:
        - "1883:1883"
        - "9001:9001"  # Optional: for WebSocket support
      restart: always
      volumes:
        - ./mosquitto:/mosquitto

  #JSON IOT Agent that supports HTTP, MQTT and AMQP
  iot-agent:
      image: fiware/iotagent-json
      hostname: iot-agent
      container_name: fiware-iot-agent
      depends_on:
          - mongodb
          - mosquitto
      expose:
          - "4041"
          - "7896"
      ports:
          - "4041:4041"
          - "7896:7896"
      environment:
          - "IOTA_CB_HOST=scorpio" # Locally hosted broker
          - "IOTA_CB_PORT=1026"
          - "IOTA_NORTH_PORT=4041"
          - "IOTA_REGISTRY_TYPE=mongodb"
          - "IOTA_MONGO_HOST=mongodb"
          - "IOTA_MONGO_PORT=27017"
          - "IOTA_MONGO_DB=iotagent-json"
          - "IOTA_HTTP_PORT=7896"
          - "IOTA_PROVIDER_URL=http://iot-agent:4041"
          - "IOTA_CB_NGSI_VERSION=LD"         # To work with NGSI-LD brokers
          - "IOTA_TIMESTAMP=true"
          - "IOTA_FALLBACK_TENANT=openiot"
          - "IOTA_FALLBACK_PATH=/"
          - "IOTA_MQTT_HOST=mosquitto"        # MQTT broker service
          - "IOTA_MQTT_PORT=1883"             # MQTT service port
          - "IOTA_JSON_LD_CONTEXT=https://uri.etsi.org/ngsi-ld/v1/ngsi-ld-core-context-v1.6.jsonld"

  #############
  # Databases #
  #############

  # Storage of context data of IOT agent
  mongodb:
      image: mongo:4.2
      hostname: mongodb
      container_name: db-mongo
      ports:
          - "27017:27017"
      command: --bind_ip_all
      volumes:
          - mongodb:/data

  # Database for Scorpio
  postgres:
    image: postgis/postgis
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ngb
      POSTGRES_PASSWORD: ngb
      POSTGRES_DB: ngb
